experiment:
  dataset: hm_random_keep0.6

  data_config:
    strategy: fixed
    train_path: ../../../data/processed/hm_random_keep0.6/train.tsv
    validation_path: ../../../data/processed/hm_random_keep0.6/valid.tsv
    test_path: ../../../data/processed/hm_random_keep0.6/test.tsv

  top_k: 50

  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics:
      - Precision
      - Recall
      - nDCG
      - MAP
      - MRR
      - SEntropy
      - Gini
      - ItemCoverage
      - ARP
      - APLT
      - Recall_pop1
      - Recall_pop2_5
      - Recall_pop6_10
      - Recall_pop11_20
      - Recall_pop20plus
      - nDCG_pop1
      - nDCG_pop2_5
      - nDCG_pop6_10
      - nDCG_pop11_20
      - nDCG_pop20plus
      - Recall_u1
      - Recall_u2_5
      - Recall_u6_10
      - Recall_u11_20
      - Recall_u20plus
      - nDCG_u1
      - nDCG_u2_5
      - nDCG_u6_10
      - nDCG_u11_20
      - nDCG_u20plus

  path_output_rec_result: ../../results/elliot/hm_random_keep0.6/recs/
  path_output_rec_performance: ../../results/elliot/hm_random_keep0.6/performance/
  path_log_folder: ../../results/elliot/hm_random_keep0.6/logs/

  gpu: -1

  models:
    FunkSVD:
      meta:
        save_recs: True
        validation_metric: nDCG@10
        validation_rate: 1
      epochs: 100
      batch_size: 512
      factors: 64
      lr: 0.0001
      reg_w: 0.1
      reg_b: 0.001
      early_stopping:
        monitor: nDCG@10
        mode: max
        patience: 10
        min_delta: 0.0001
        verbose: True
